export const DIPLOMAS = [
  "Diploma di Liceo Classico",
  "Diploma di Liceo Scientifico",
  "Diploma di Liceo Linguistico",
  "Diploma di Liceo delle Scienze Umane",
  "Diploma di Liceo Artistico",
  "Diploma di Liceo Musicale e Coreutico",
  "Diploma di Amministrazione, Finanza e Marketing",
  "Diploma di Turismo",
  "Diploma di Meccanica, Meccatronica ed Energia",
  "Diploma di Trasporti e Logistica",
  "Diploma di Elettronica ed Elettrotecnica",
  "Diploma di Informatica e Telecomunicazioni",
  "Diploma di Grafica e Comunicazione",
  "Diploma di Chimica, Materiali e Biotecnologie",
  "Diploma di Sistema Moda",
  "Diploma di Agraria, Agroalimentare e Agroindustria",
  "Diploma di Costruzioni, Ambiente e Territorio",
  "Diploma di Agricoltura, sviluppo rurale, valorizzazione dei prodotti del territorio e gestione delle risorse forestali e montane",
  "Diploma di Pesca commerciale e produzioni ittiche",
  "Diploma di Industria e Artigianato per il Made in Italy",
  "Diploma di Manutenzione e Assistenza Tecnica",
  "Diploma di Gestione delle Acque e Risanamento Ambientale",
  "Diploma di Servizi Commerciali",
  "Diploma di Enogastronomia e Ospitalità Alberghiera",
  "Diploma di Servizi Culturali e dello Spettacolo",
  "Diploma di Servizi per la Sanità e l'Assistenza Sociale",
  "Diploma di Arti Ausiliarie delle Professioni Sanitarie – Odontotecnico",
  "Diploma di Arti Ausiliarie delle Professioni Sanitarie – Ottico",
  "Diploma Professionale di Operatore Agricolo",
  "Diploma Professionale di Operatore della Trasformazione Agroalimentare",
  "Diploma Professionale di Operatore dell'Abbigliamento",
  "Diploma Professionale di Operatore delle Calzature",
  "Diploma Professionale di Operatore del Legno",
  "Diploma Professionale di Operatore del Mobile",
  "Diploma Professionale di Operatore Meccanico",
  "Diploma Professionale di Operatore Elettrico",
  "Diploma Professionale di Operatore Elettronico",
  "Diploma Professionale di Operatore alla Riparazione dei Veicoli a Motore",
  "Diploma Professionale di Operatore degli Impianti Termoidraulici",
  "Diploma Professionale di Operatore Edile",
  "Diploma Professionale di Operatore Grafico",
  "Diploma Professionale di Operatore della Ristorazione",
  "Diploma Professionale di Operatore ai Servizi di Promozione e Accoglienza",
  "Diploma Professionale di Operatore del Benessere",
  "Diploma Professionale di Operatore Amministrativo-Segretariale",
  "Diploma Professionale di Operatore ai Servizi di Vendita",
  "Diploma Professionale di Operatore dei Sistemi e dei Servizi Logistici",
  "Diploma Professionale di Operatore della Comunicazione Multimediale",
  "Diploma Professionale di Operatore Informatico"
];

export const DEGREES = [
  "Laurea in Agraria",
  "Laurea in Architettura",
  "Laurea in Beni Culturali",
  "Laurea in Biologia",
  "Laurea in Biotecnologie",
  "Laurea in Chimica",
  "Laurea in Chimica Industriale",
  "Laurea in Conservazione e Restauro dei Beni Culturali",
  "Laurea in Design",
  "Laurea in Economia Aziendale",
  "Laurea in Economia e Commercio",
  "Laurea in Economia e Finanza",
  "Laurea in Educazione Professionale",
  "Laurea in Farmacia",
  "Laurea in Filosofia",
  "Laurea in Fisica",
  "Laurea in Fisioterapia",
  "Laurea in Giurisprudenza",
  "Laurea in Igiene Dentale",
  "Laurea in Informatica",
  "Laurea in Infermieristica",
  "Laurea in Ingegneria Aerospaziale",
  "Laurea in Ingegneria Biomedica",
  "Laurea in Ingegneria Chimica",
  "Laurea in Ingegneria Civile",
  "Laurea in Ingegneria Edile",
  "Laurea in Ingegneria Elettrica",
  "Laurea in Ingegneria Elettronica",
  "Laurea in Ingegneria Gestionale",
  "Laurea in Ingegneria Informatica",
  "Laurea in Ingegneria Meccanica",
  "Laurea in Ingegneria Navale",
  "Laurea in Ingegneria per l'Ambiente e il Territorio",
  "Laurea in Lettere",
  "Laurea in Lingue e Letterature Straniere",
  "Laurea in Logopedia",
  "Laurea in Matematica",
  "Laurea in Medicina e Chirurgia",
  "Laurea in Medicina Veterinaria",
  "Laurea in Odontoiatria e Protesi Dentaria",
  "Laurea in Ostetricia",
  "Laurea in Psicologia",
  "Laurea in Scienze Ambientali",
  "Laurea in Scienze Biologiche",
  "Laurea in Scienze della Comunicazione",
  "Laurea in Scienze dell'Educazione e della Formazione",
  "Laurea in Scienze del Servizio Sociale",
  "Laurea in Scienze delle Attività Motorie e Sportive",
  "Laurea in Scienze della Nutrizione",
  "Laurea in Scienze e Tecniche Psicologiche",
  "Laurea in Scienze Economiche",
  "Laurea in Scienze Forestali",
  "Laurea in Scienze Geologiche",
  "Laurea in Scienze Internazionali e Diplomatiche",
  "Laurea in Scienze Naturali",
  "Laurea in Scienze Politiche",
  "Laurea in Scienze Statistiche",
  "Laurea in Servizio Sociale",
  "Laurea in Sociologia",
  "Laurea in Storia",
  "Laurea in Tecniche di Laboratorio Biomedico",
  "Laurea in Tecniche di Radiologia Medica per Immagini e Radioterapia",
  "Laurea in Tecniche della Prevenzione nell'Ambiente e nei Luoghi di Lavoro",
  "Laurea in Terapia Occupazionale",
  "Laurea in Terapia della Neuro e Psicomotricità dell'Età Evolutiva",
  "Laurea in Turismo",
  "Laurea in Urbanistica",
  "Altra Laurea"
];

export const PROFESSIONS = [
  "Accompagnatore Turistico",
  "Addetto Acquisti",
  "Addetto alla Clientela",
  "Addetto alla Logistica",
  "Addetto alla Produzione",
  "Addetto alle Pulizie",
  "Addetto alle Vendite",
  "Addetto Call Center",
  "Addetto Controllo Qualità",
  "Addetto Magazzino",
  "Addetto Marketing",
  "Addetto Risorse Umane",
  "Agente Assicurativo",
  "Agente Immobiliare",
  "Agente di Commercio",
  "Agricoltore",
  "Allenatore Sportivo",
  "Amministratore",
  "Analista Dati",
  "Analista Finanziario",
  "Animatore",
  "Archeologo",
  "Architetto",
  "Arredatore",
  "Artigiano",
  "Ascensorista",
  "Assistente Amministrativo",
  "Assistente Clienti",
  "Assistente Commerciale",
  "Assistente Familiare",
  "Assistente Sociale",
  "Assistente di Direzione",
  "Attore",
  "Autista",
  "Autotrasportatore",
  "Avvocato",
  "Babysitter",
  "Badante",
  "Barbiere",
  "Barista",
  "Bibliotecario",
  "Biologo",
  "Broker Assicurativo",
  "Cameriere",
  "Cameriere ai Piani",
  "Cantiniere",
  "Carpentiere",
  "Carrozziere",
  "Cassiere",
  "Chef",
  "Chimico",
  "Collaboratore Domestico",
  "Collaudatore",
  "Commesso",
  "Commercialista",
  "Consulente",
  "Consulente Aziendale",
  "Consulente Finanziario",
  "Consulente Informatico",
  "Consulente del Lavoro",
  "Contabile",
  "Copywriter",
  "Corriere",
  "Cuoco",
  "Custode",
  "Designer",
  "Dietista",
  "Direttore",
  "Direttore Commerciale",
  "Direttore Vendite",
  "Docente",
  "Educatore",
  "Elettrauto",
  "Elettricista",
  "Estetista",
  "Farmacista",
  "Falegname",
  "Fattorino",
  "Fisioterapista",
  "Fotografo",
  "Geologo",
  "Geometra",
  "Giornalista",
  "Giardiniere",
  "Governante",
  "Grafico",
  "Hostess",
  "Idraulico",
  "Illustratore",
  "Imbianchino",
  "Impiegato",
  "Impiegato Amministrativo",
  "Impiegato Commerciale",
  "Impiegato Contabile",
  "Impiegato Tecnico",
  "Imprenditore",
  "Infermiere",
  "Informatico",
  "Ingegnere",
  "Insegnante",
  "Installatore",
  "Interprete",
  "Investigatore Privato",
  "Lavapiatti",
  "Legale",
  "Logopedista",
  "Magazziniere",
  "Make-up Artist",
  "Manager",
  "Manutentore",
  "Massaggiatore",
  "Meccanico",
  "Mediatore",
  "Medico",
  "Montatore",
  "Muratore",
  "Musicista",
  "Notaio",
  "Nutrizionista",
  "Odontoiatra",
  "Operaio",
  "Operaio Agricolo",
  "Operaio Edile",
  "Operatore Call Center",
  "Operatore CAF",
  "Operatore Ecologico",
  "Operatore Socio Sanitario (OSS)",
  "Operatore Turistico",
  "Ortodontista",
  "Orafo",
  "Ostetrica",
  "Panettiere",
  "Parrucchiere",
  "Pasticcere",
  "Perito",
  "Personal Trainer",
  "Pescatore",
  "Pizzaiolo",
  "Portiere",
  "Programmatore",
  "Project Manager",
  "Promoter",
  "Psicologo",
  "Pubblicitario",
  "Receptionist",
  "Responsabile Acquisti",
  "Responsabile Amministrativo",
  "Responsabile Commerciale",
  "Responsabile Logistica",
  "Responsabile Marketing",
  "Responsabile Produzione",
  "Ricercatore",
  "Saldatore",
  "Sarto",
  "Scaffalista",
  "Segretario",
  "Serramentista",
  "Serramentista Metallico",
  "Sistemista",
  "Sviluppatore Software",
  "Tecnico Audio",
  "Tecnico Elettronico",
  "Tecnico Informatico",
  "Tecnico Manutentore",
  "Tecnico Meccanico",
  "Tecnico di Laboratorio",
  "Tecnico di Radiologia",
  "Traduttore",
  "Verniciatore",
  "Veterinario",
  "Videomaker",
  "Vivaista",
  "Web Designer",
  "Web Developer",
  "Webmaster",
  "Zootecnico"
];

export const CITIES = [
  "Agrigento",
  "Alessandria",
  "Ancona",
  "Aosta",
  "Arezzo",
  "Ascoli Piceno",
  "Asti",
  "Avellino",
  "Bari",
  "Barletta",
  "Belluno",
  "Benevento",
  "Bergamo",
  "Biella",
  "Bologna",
  "Bolzano",
  "Brescia",
  "Brindisi",
  "Cagliari",
  "Caltanissetta",
  "Campobasso",
  "Caserta",
  "Catania",
  "Catanzaro",
  "Chieti",
  "Como",
  "Cosenza",
  "Cremona",
  "Crotone",
  "Cuneo",
  "Enna",
  "Fermo",
  "Ferrara",
  "Firenze",
  "Foggia",
  "Forlì",
  "Frosinone",
  "Genova",
  "Gorizia",
  "Grosseto",
  "Imperia",
  "Isernia",
  "L'Aquila",
  "La Spezia",
  "Latina",
  "Lecce",
  "Lecco",
  "Livorno",
  "Lodi",
  "Lucca",
  "Macerata",
  "Mantova",
  "Massa",
  "Matera",
  "Messina",
  "Milano",
  "Modena",
  "Monza",
  "Napoli",
  "Novara",
  "Nuoro",
  "Oristano",
  "Padova",
  "Palermo",
  "Parma",
  "Pavia",
  "Perugia",
  "Pesaro",
  "Pescara",
  "Piacenza",
  "Pisa",
  "Pistoia",
  "Pordenone",
  "Potenza",
  "Prato",
  "Ragusa",
  "Ravenna",
  "Reggio Calabria",
  "Reggio Emilia",
  "Rieti",
  "Rimini",
  "Roma",
  "Rovigo",
  "Salerno",
  "Sassari",
  "Savona",
  "Siena",
  "Siracusa",
  "Sondrio",
  "Sud Sardegna",
  "Taranto",
  "Teramo",
  "Terni",
  "Torino",
  "Trapani",
  "Trento",
  "Treviso",
  "Trieste",
  "Udine",
  "Varese",
  "Venezia",
  "Verbano-Cusio-Ossola",
  "Vercelli",
  "Verona",
  "Vibo Valentia",
  "Vicenza",
  "Viterbo"
];

export const REGIONS_AND_PROVINCES: Record<string, string[]> = {
  "Abruzzo": ["L'Aquila", "Chieti", "Pescara", "Teramo", "Tutte le province"],
  "Basilicata": ["Matera", "Potenza", "Tutte le province"],
  "Calabria": ["Catanzaro", "Cosenza", "Crotone", "Reggio Calabria", "Vibo Valentia", "Tutte le province"],
  "Campania": ["Avellino", "Benevento", "Caserta", "Napoli", "Salerno", "Tutte le province"],
  "Emilia-Romagna": ["Bologna", "Ferrara", "Forlì-Cesena", "Modena", "Parma", "Piacenza", "Ravenna", "Reggio Emilia", "Rimini", "Tutte le province"],
  "Friuli Venezia Giulia": ["Gorizia", "Pordenone", "Trieste", "Udine", "Tutte le province"],
  "Lazio": ["Frosinone", "Latina", "Rieti", "Roma", "Viterbo", "Tutte le province"],
  "Liguria": ["Genova", "Imperia", "La Spezia", "Savona", "Tutte le province"],
  "Lombardia": ["Bergamo", "Brescia", "Como", "Cremona", "Lecco", "Lodi", "Mantova", "Milano", "Monza e della Brianza", "Pavia", "Sondrio", "Varese", "Tutte le province"],
  "Marche": ["Ancona", "Ascoli Piceno", "Fermo", "Macerata", "Pesaro e Urbino", "Tutte le province"],
  "Molise": ["Campobasso", "Isernia", "Tutte le province"],
  "Piemonte": ["Alessandria", "Asti", "Biella", "Cuneo", "Novara", "Torino", "Verbano-Cusio-Ossola", "Vercelli", "Tutte le province"],
  "Puglia": ["Bari", "Barletta-Andria-Trani", "Brindisi", "Foggia", "Lecce", "Taranto", "Tutte le province"],
  "Sardegna": ["Cagliari", "Nuoro", "Oristano", "Sassari", "Sud Sardegna", "Tutte le province"],
  "Sicilia": ["Agrigento", "Caltanissetta", "Catania", "Enna", "Messina", "Palermo", "Ragusa", "Siracusa", "Trapani", "Tutte le province"],
  "Toscana": ["Arezzo", "Firenze", "Grosseto", "Livorno", "Lucca", "Massa-Carrara", "Pisa", "Pistoia", "Prato", "Siena", "Tutte le province"],
  "Trentino-Alto Adige/Südtirol": ["Bolzano", "Trento", "Tutte le province"],
  "Umbria": ["Perugia", "Terni", "Tutte le province"],
  "Valle d'Aosta/Vallée d'Aoste": ["Aosta", "Tutte le province"],
  "Veneto": ["Belluno", "Padova", "Rovigo", "Treviso", "Venezia", "Verona", "Vicenza", "Tutte le province"],
  "Tutte le regioni": []
};

export const COMPUTER_SKILLS_LIST = [
  "Windows",
  "macOS",
  "Linux",
  "Pacchetto Microsoft Office (Word, Excel, PowerPoint, Outlook)",
  "Google Workspace",
  "Cloud (Google Drive, OneDrive, Dropbox)",
  "Microsoft Teams",
  "Zoom",
  "Canva",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "WordPress",
  "HTML/CSS",
  "JavaScript",
  "Python",
  "Java",
  "C#",
  "PHP",
  "SQL",
  "Git / GitHub",
  "Power BI",
  "Tableau",
  "SAP",
  "Salesforce",
  "AutoCAD",
  "SolidWorks",
  "Docker",
  "VMware / VirtualBox",
  "AWS",
  "Microsoft Azure",
  "Google Cloud Platform",
  "ChatGPT e strumenti di IA",
  "Power Automate",
  "GitHub Copilot"
];

export const ORGANIZATIONAL_SKILLS_LIST = [
  { name: "Organizzazione del lavoro", description: "Capacità di pianificare, organizzare e svolgere le attività lavorative in modo ordinato ed efficiente." },
  { name: "Pianificazione delle attività", description: "Capacità di definire obiettivi, stabilire priorità e programmare le attività nel rispetto delle scadenze." },
  { name: "Gestione del tempo", description: "Capacità di utilizzare efficacemente il tempo disponibile, rispettando tempi e priorità operative." },
  { name: "Gestione delle priorità", description: "Capacità di individuare le attività più urgenti o strategiche e organizzare il lavoro di conseguenza." },
  { name: "Problem solving", description: "Capacità di analizzare situazioni complesse, individuare criticità e proporre soluzioni efficaci." },
  { name: "Coordinamento delle attività", description: "Capacità di organizzare e coordinare il lavoro proprio o di un gruppo per il raggiungimento degli obiettivi." },
  { name: "Gestione di progetti", description: "Capacità di pianificare, monitorare e portare a termine progetti nel rispetto di tempi, costi e risultati attesi." },
  { name: "Gestione delle scadenze", description: "Capacità di rispettare tempi di consegna e obiettivi prefissati mantenendo elevati standard qualitativi." },
  { name: "Organizzazione documentale", description: "Capacità di archiviare, classificare e gestire documentazione cartacea e digitale in modo efficiente." },
  { name: "Precisione operativa", description: "Capacità di svolgere le attività con attenzione ai dettagli, riducendo errori e imprecisioni." },
  { name: "Gestione di attività multiple", description: "Capacità di gestire contemporaneamente più incarichi mantenendo qualità ed efficienza." },
  { name: "Capacità decisionale", description: "Capacità di prendere decisioni tempestive e motivate anche in situazioni di incertezza." },
  { name: "Orientamento agli obiettivi", description: "Capacità di pianificare e svolgere il lavoro con costante attenzione al raggiungimento dei risultati prefissati." },
  { name: "Ottimizzazione dei processi", description: "Capacità di individuare opportunità di miglioramento nell'organizzazione del lavoro e nei processi operativi." },
  { name: "Gestione delle risorse", description: "Capacità di utilizzare in modo efficiente risorse umane, economiche e materiali per il raggiungimento degli obiettivi." },
  { name: "Adattamento ai cambiamenti organizzativi", description: "Capacità di riorganizzare il proprio lavoro in risposta a nuove esigenze, procedure o contesti lavorativi." }
];

export const COMMUNICATIVE_SKILLS_LIST = [
  { name: "Comunicazione verbale", description: "Esporre idee e informazioni in modo chiaro." },
  { name: "Ascolto attivo", description: "Comprendere gli altri prestando attenzione e ponendo domande pertinenti." },
  { name: "Lavoro di squadra", description: "Collaborare efficacemente con colleghi e gruppi di lavoro." },
  { name: "Relazioni con il pubblico", description: "Interagire con clienti, utenti o cittadini in modo professionale." },
  { name: "Gestione dei conflitti", description: "Affrontare e risolvere disaccordi in modo costruttivo." },
  { name: "Empatia", description: "Comprendere esigenze e punti di vista degli altri." },
  { name: "Capacità di negoziazione", description: "Raggiungere accordi e mediare tra diverse esigenze." },
  { name: "Public speaking", description: "Parlare in pubblico con sicurezza ed efficacia." },
  { name: "Orientamento al cliente/utente", description: "Offrire supporto e assistenza con attenzione e cortesia." },
  { name: "Capacità di collaborazione", description: "Condividere informazioni e contribuire agli obiettivi comuni." }
];

export const LANGUAGE_SKILLS_LIST = [
  "Italiano",
  "Inglese",
  "Francese"
];

export const PROVINCE_SIGLE: Record<string, string> = {
  "Agrigento": "AG",
  "Alessandria": "AL",
  "Ancona": "AN",
  "Aosta": "AO",
  "Arezzo": "AR",
  "Ascoli Piceno": "AP",
  "Asti": "AT",
  "Avellino": "AV",
  "Bari": "BA",
  "Barletta-Andria-Trani": "BT",
  "Belluno": "BL",
  "Benevento": "BN",
  "Bergamo": "BG",
  "Biella": "BI",
  "Bologna": "BO",
  "Bolzano": "BZ",
  "Brescia": "BS",
  "Brindisi": "BR",
  "Cagliari": "CA",
  "Caltanissetta": "CL",
  "Campobasso": "CB",
  "Caserta": "CE",
  "Catania": "CT",
  "Catanzaro": "CZ",
  "Chieti": "CH",
  "Como": "CO",
  "Cosenza": "CS",
  "Cremona": "CR",
  "Crotone": "KR",
  "Cuneo": "CN",
  "Enna": "EN",
  "Fermo": "FM",
  "Ferrara": "FE",
  "Firenze": "FI",
  "Foggia": "FG",
  "Forlì-Cesena": "FC",
  "Frosinone": "FR",
  "Genova": "GE",
  "Gorizia": "GO",
  "Grosseto": "GR",
  "Imperia": "IM",
  "Isernia": "IS",
  "L'Aquila": "AQ",
  "La Spezia": "SP",
  "Latina": "LT",
  "Lecce": "LE",
  "Lecco": "LC",
  "Livorno": "LI",
  "Lodi": "LO",
  "Lucca": "LU",
  "Macerata": "MC",
  "Mantova": "MN",
  "Massa-Carrara": "MS",
  "Matera": "MT",
  "Messina": "ME",
  "Milano": "MI",
  "Modena": "MO",
  "Monza e della Brianza": "MB",
  "Napoli": "NA",
  "Novara": "NO",
  "Nuoro": "NU",
  "Oristano": "OR",
  "Padova": "PD",
  "Palermo": "PA",
  "Parma": "PR",
  "Pavia": "PV",
  "Perugia": "PG",
  "Pesaro e Urbino": "PU",
  "Pescara": "PE",
  "Piacenza": "PC",
  "Pisa": "PI",
  "Pistoia": "PT",
  "Pordenone": "PN",
  "Potenza": "PZ",
  "Prato": "PO",
  "Ragusa": "RG",
  "Ravenna": "RA",
  "Reggio Calabria": "RC",
  "Reggio Emilia": "RE",
  "Rieti": "RI",
  "Rimini": "RN",
  "Roma": "RM",
  "Rovigo": "RO",
  "Salerno": "SA",
  "Sassari": "SS",
  "Savona": "SV",
  "Siena": "SI",
  "Siracusa": "SR",
  "Sondrio": "SO",
  "Sud Sardegna": "SU",
  "Taranto": "TA",
  "Teramo": "TE",
  "Terni": "TR",
  "Torino": "TO",
  "Trapani": "TP",
  "Trento": "TN",
  "Treviso": "TV",
  "Trieste": "TS",
  "Udine": "UD",
  "Varese": "VA",
  "Venezia": "VE",
  "Verbano-Cusio-Ossola": "VB",
  "Vercelli": "VC",
  "Verona": "VR",
  "Vibo Valentia": "VV",
  "Vicenza": "VI",
  "Viterbo": "VT"
};

export const UNIVERSITIES = [
  "Gran Sasso Science Institute (L'Aquila)",
  "Humanitas University (Pieve Emanuele - MI)",
  "IMT - Scuola IMT Alti Studi Lucca",
  "Istituto Universitario di Studi Superiori (IUSS Pavia)",
  "Libera Università \"Maria SS. Assunta\" (LUMSA Roma)",
  "Libera Università di Bolzano",
  "Libera Università di Lingue e Comunicazione (IULM Milano)",
  "Libera Università Internazionale degli Studi Sociali \"Guido Carli\" (LUISS Roma)",
  "LUM Università \"Giuseppe Degennaro\" (Casamassima - BA)",
  "Politecnico di Bari",
  "Politecnico di Milano",
  "Politecnico di Torino",
  "Scuola IMT Alti Studi Lucca",
  "Scuola Internazionale Superiore di Studi Avanzati (SISSA Trieste)",
  "Scuola Normale Superiore (Pisa)",
  "Scuola Superiore di Studi Universitari e di Perfezionamento Sant'Anna (Pisa)",
  "UniCamillus - Saint Camillus International University of Health and Medical Sciences (Roma)",
  "Università \"Carlo Cattaneo\" (LIUC Castellanza - VA)",
  "Università Campus Bio-Medico di Roma",
  "Università Commerciale \"Luigi Bocconi\" (Milano)",
  "Università degli Studi \"Gabriele d'Annunzio\" (Chieti-Pescara)",
  "Università degli Studi \"Giustino Fortunato\" (Telematica - Benevento)",
  "Università degli Studi \"Magna Graecia\" (Catanzaro)",
  "Università degli Studi \"Mediterranea\" (Reggio Calabria)",
  "Università degli Studi \"Niccolò Cusano\" (Telematica - Roma)",
  "Università degli Studi \"Suor Orsola Benincasa\" (Napoli)",
  "Università degli Studi della Basilicata (Potenza)",
  "Università degli Studi della Calabria (Rende - CS)",
  "Università degli Studi della Campania \"Luigi Vanvitelli\" (Caserta)",
  "Università degli Studi della Tuscia (Viterbo)",
  "Università degli Studi dell'Aquila",
  "Università degli Studi dell'Insubria (Varese-Como)",
  "Università degli Studi del Molise (Campobasso)",
  "Università degli Studi del Piemonte Orientale \"Amedeo Avogadro\" (Vercelli)",
  "Università degli Studi del Sannio (Benevento)",
  "Università degli Studi di Bari \"Aldo Moro\"",
  "Università degli Studi di Bergamo",
  "Università degli Studi di Bologna",
  "Università degli Studi di Brescia",
  "Università degli Studi di Cagliari",
  "Università degli Studi di Camerino",
  "Università degli Studi di Cassino e del Lazio Meridionale",
  "Università degli Studi di Catania",
  "Università degli Studi di Ferrara",
  "Università degli Studi di Firenze",
  "Università degli Studi di Foggia",
  "Università degli Studi di Genova",
  "Università degli Studi di Macerata",
  "Università degli Studi di Messina",
  "Università degli Studi di Milano",
  "Università degli Studi di Milano-Bicocca",
  "Università degli Studi di Modena e Reggio Emilia",
  "Università degli Studi di Napoli \"Federico II\"",
  "Università degli Studi di Napoli \"L'Orientale\"",
  "Università degli Studi di Napoli \"Parthenope\"",
  "Università degli Studi di Padova",
  "Università degli Studi di Palermo",
  "Università degli Studi di Parma",
  "Università degli Studi di Pavia",
  "Università degli Studi di Perugia",
  "Università degli Studi di Pisa",
  "Università degli Studi di Reggio Calabria \"Mediterranea\"",
  "Università degli Studi di Roma \"Foro Italico\"",
  "Università degli Studi di Roma \"La Sapienza\"",
  "Università degli Studi di Roma \"Tor Vergata\"",
  "Università degli Studi di Roma Tre",
  "Università degli Studi di Salerno (Fisciano - SA)",
  "Università degli Studi di Sassari",
  "Università degli Studi di Siena",
  "Università degli Studi di Teramo",
  "Università degli Studi di Torino",
  "Università degli Studi di Trento",
  "Università degli Studi di Trieste",
  "Università degli Studi di Udine",
  "Università degli Studi di Urbino \"Carlo Bo\"",
  "Università degli Studi di Verona",
  "Università degli Studi di Scienze Gastronomiche (Bra - CN)",
  "Università degli Studi Link (Roma)",
  "Università Cattolica del Sacro Cuore (Milano)",
  "Università Europea di Roma",
  "Università Iuav di Venezia",
  "Università per Stranieri \"Dante Alighieri\" (Reggio Calabria)",
  "Università per Stranieri di Perugia",
  "Università per Stranieri di Siena",
  "Università San Raffaele (Telematica - Roma)",
  "Università Telematica \"Guglielmo Marconi\" (Roma)",
  "Università Telematica \"Italian University Line\" (IUL Firenze)",
  "Università Telematica \"Leonardo da Vinci\" (Torrevecchia Teatina - CH)",
  "Università Telematica \"Pegaso\" (Napoli)",
  "Università Telematica Internazionale \"UniNettuno\" (Roma)",
  "Università Telematica e-Campus (Novedrate - CO)",
  "Università Telematica Unitelma Sapienza (Roma)",
  "Università Vita-Salute San Raffaele (Milano)"
];

export const COMPANY_SECTORS = [
  "Agricoltura",
  "Allevamento",
  "Pesca e acquacoltura",
  "Estrazione mineraria",
  "Industria manifatturiera",
  "Produzione alimentare",
  "Produzione tessile",
  "Produzione chimica",
  "Produzione farmaceutica",
  "Metalmeccanica",
  "Edilizia e costruzioni",
  "Energia",
  "Gas",
  "Acqua e gestione rifiuti",
  "Commercio all'ingrosso",
  "Commercio al dettaglio",
  "E-commerce",
  "Import/Export",
  "Trasporti",
  "Logistica",
  "Magazzinaggio",
  "Servizi postali e corrieri",
  "Informatica",
  "Sviluppo software",
  "Telecomunicazioni",
  "Consulenza informatica",
  "Servizi digitali",
  "Finanza",
  "Assicurazioni",
  "Immobiliare",
  "Consulenza aziendale",
  "Studi professionali",
  "Attività legali",
  "Contabilità e revisione",
  "Ingegneria",
  "Architettura",
  "Ricerca scientifica",
  "Pubblicità",
  "Marketing",
  "Comunicazione",
  "Design",
  "Formazione",
  "Istruzione",
  "Sanità",
  "Assistenza sociale",
  "Farmacie",
  "Turismo",
  "Alberghi",
  "Ristorazione",
  "Bar e caffetterie",
  "Agenzie di viaggio",
  "Sport",
  "Intrattenimento",
  "Cultura",
  "Editoria",
  "Cinema e audiovisivo",
  "Musica",
  "Eventi",
  "Sicurezza privata",
  "Pulizie",
  "Vigilanza",
  "Servizi ambientali",
  "Riparazioni e manutenzione",
  "Parrucchieri ed estetica",
  "Servizi alla persona",
  "Organizzazioni no profit",
  "Pubblica amministrazione"
];

